import { useState, useEffect } from 'react'
import { Button } from '../../../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card'
import { Download, FileText, Eye, CheckCircle, XCircle, AlertCircle, Loader2, Printer } from 'lucide-react'
import { toast } from 'sonner'
import jsPDF from 'jspdf'
import { PDFGeneratorProps } from '../types'

// Canvas-based template configuration
interface CanvasTemplate {
  id: string
  name: string
  description: string
  baseImagePath: string
  size: 'A4' | 'A3'
  orientation: 'portrait' | 'landscape'
  // Coordinates in mm for A4 (210x297mm)
  logoPosition: { x: number; y: number } // center point
  qrPosition: { x: number; y: number; width: number; height: number }
}

interface TextPart {
  text: string
  bold: boolean
}

const CANVAS_TEMPLATES: CanvasTemplate[] = [
  {
    id: 'colella-template-a4',
    name: 'Colella Template A4',
    description: 'Professional template with precise logo and QR positioning',
    baseImagePath: '/images/pdf_template_bases/base1.png',
    size: 'A4',
    orientation: 'portrait',
    logoPosition: { x: 105, y: 84.5 }, // center point in mm (centered between 72mm and 97mm = 84.5mm)
    qrPosition: { x: 150, y: 241, width: 33, height: 33 } // top-left position and size in mm
  },
  {
    id: 'colella-template-a3',
    name: 'Colella Template A3',
    description: 'Large format version with precise positioning',
    baseImagePath: '/images/pdf_template_bases/base1.png',
    size: 'A3',
    orientation: 'portrait',
    logoPosition: { x: 148.5, y: 120 }, // center point between 102mm and 138mm = 120mm
    qrPosition: { x: 212, y: 341, width: 46, height: 46 } // top-left at 212mm, 341mm, 46mm square
  }
]

export function PDFGenerator({ partnerData, qrCodeUrl, logoUrl, onGenerate }: PDFGeneratorProps) {
  const [selectedSize, setSelectedSize] = useState<'A4' | 'A3'>('A4')
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedPdfUrl, setGeneratedPdfUrl] = useState<string | null>(null)

  const [autoGeneratedQrUrl, setAutoGeneratedQrUrl] = useState<string | null>(null)


  const businessName = partnerData?.business_name || partnerData?.full_name || 'Your Business'

  // Get the selected template based on size
  const selectedCanvasTemplate = CANVAS_TEMPLATES.find(t => t.size === selectedSize) || CANVAS_TEMPLATES[0]

  // Auto-generate QR code if partner data exists but no QR code provided
  useEffect(() => {
    const generateQRCode = async () => {
      if (partnerData?.partner_code && !qrCodeUrl && !autoGeneratedQrUrl) {
        try {
          // Import QRCode dynamically to avoid SSR issues
          const QRCode = (await import('qrcode')).default
          const referralUrl = `https://colellapartners.com.au/refer/${partnerData.partner_code}`
          
          const qrDataUrl = await QRCode.toDataURL(referralUrl, {
            width: 256,
            margin: 1,
            color: {
              dark: '#000029',
              light: '#FFFFFF'
            }
          })
          
          setAutoGeneratedQrUrl(qrDataUrl)
        } catch (_error) {
          // Silently fail QR code generation
        }
      }
    }

    generateQRCode()
  }, [partnerData?.partner_code, qrCodeUrl, autoGeneratedQrUrl])

  // Cleanup PDF URL when component unmounts
  useEffect(() => {
    return () => {
      if (generatedPdfUrl) {
        URL.revokeObjectURL(generatedPdfUrl)
      }
    }
  }, [generatedPdfUrl])

  // Use provided QR code or auto-generated one
  const effectiveQrCodeUrl = qrCodeUrl || autoGeneratedQrUrl
  
  // Check if all requirements are met
  const canGenerate = partnerData && effectiveQrCodeUrl

  // Convert mm to pixels at 300 DPI (print quality)
  const mmToPixels = (mm: number): number => {
    return Math.round((mm * 300) / 25.4) // 300 DPI conversion
  }

  // Load image from URL/path
  const loadImage = (src: string): Promise<HTMLImageElement> => {
    return new Promise((resolve, reject) => {
      const img = new Image()
      
      // Only set crossOrigin for external URLs, not for local files or data URLs
      if (src.startsWith('http') && !src.startsWith(window.location.origin)) {
        img.crossOrigin = 'anonymous'
      }
      
      img.onload = () => {
        resolve(img)
      }
      
      img.onerror = () => {
        reject(new Error(`Failed to load image: ${src}`))
      }
      
      img.src = src
    })
  }

  // Load custom font
  const loadFont = async (fontName: string, fontPath: string): Promise<FontFace> => {
    const fontFace = new FontFace(fontName, `url(${fontPath})`)
    const loadedFont = await fontFace.load()
    document.fonts.add(loadedFont)
    return loadedFont
  }

  // Add text content to canvas
  const addTextContent = async (ctx: CanvasRenderingContext2D, template: CanvasTemplate) => {
    // Load custom fonts
    try {
      await loadFont('AdriannaExtended-Regular', '/fonts/AdriannaExtended-Regular.ttf')
      await loadFont('AdriannaExtended-Bold', '/fonts/AdriannaExtended-Bold.ttf')
    } catch (_error) {
      // Use fallback fonts if custom fonts fail to load
    }

    // Text positioning (top-left corner) - different for A4 vs A3
    const textX = template.size === 'A4' ? mmToPixels(20) : mmToPixels(28) // 20mm for A4, 28mm for A3
    const textY = template.size === 'A4' ? mmToPixels(166) : mmToPixels(235) // 166mm for A4 (+2mm), 235mm for A3 (+4mm)
    const maxWidth = template.size === 'A4' ? mmToPixels(96) : mmToPixels(140) // 96mm for A4, 140mm for A3
    
    // Font size conversion - different for A4 vs A3
    const fontSize = template.size === 'A4' 
      ? Math.round((14 / 72) * 300) // A4: 14pt → 300 DPI pixels (58px)
      : Math.round((19.8 / 72) * 300) // A3: 19.8pt → 300 DPI pixels (82.5px)
    const lineHeight = fontSize * 1.4 // 1.4x line height for readability

    // Text content with business name
    const businessName = partnerData?.business_name || partnerData?.full_name || 'Your Business'
    const textContent = `${businessName} and Colella have teamed up to **support our community!**

List your home **for sale or lease with Colella** and support your favourite local cause!`

    // Parse text with bold formatting
    const parseTextWithBold = (text: string): TextPart[] => {
      const parts: TextPart[] = []
      const regex = /\*\*(.*?)\*\*/g
      let lastIndex = 0
      let match

      while ((match = regex.exec(text)) !== null) {
        // Add regular text before the bold part
        if (match.index > lastIndex) {
          parts.push({
            text: text.substring(lastIndex, match.index),
            bold: false
          })
        }
        
        // Add the bold part
        parts.push({
          text: match[1],
          bold: true
        })
        
        lastIndex = regex.lastIndex
      }
      
      // Add remaining text after the last bold part
      if (lastIndex < text.length) {
        parts.push({
          text: text.substring(lastIndex),
          bold: false
        })
      }
      
      return parts
    }

    // Split text into lines and handle word wrapping
    const wrapText = (textParts: TextPart[], maxWidth: number): TextPart[][] => {
      const lines: TextPart[][] = []
      let currentLine: TextPart[] = []
      let currentWidth = 0

      for (const part of textParts) {
        // Split on both spaces and newlines, but preserve them
        const segments = part.text.split(/(\s+|\n+)/)
        
        for (const segment of segments) {
          if (segment.includes('\n')) {
            // Force line break for newlines
            if (currentLine.length > 0) {
              lines.push([...currentLine])
              currentLine = []
              currentWidth = 0
            }
            // Add empty lines for multiple newlines
            const newlineCount = (segment.match(/\n/g) || []).length
            for (let i = 1; i < newlineCount; i++) {
              lines.push([])
            }
            continue
          }
          
          if (segment.trim() === '') {
            // Handle spaces - add to current line if not empty
            if (currentLine.length > 0 && segment.length > 0) {
              currentLine.push({ text: segment, bold: part.bold })
              // Measure space width
              ctx.font = `${fontSize}px ${part.bold ? 'AdriannaExtended-Bold' : 'AdriannaExtended-Regular'}, Arial, sans-serif`
              currentWidth += ctx.measureText(segment).width
            }
            continue
          }

          // Split segment into individual words
          const words = segment.split(/\s+/).filter(word => word.length > 0)
          
          for (const word of words) {
            // Set font for measuring
            ctx.font = `${fontSize}px ${part.bold ? 'AdriannaExtended-Bold' : 'AdriannaExtended-Regular'}, Arial, sans-serif`
            const wordWidth = ctx.measureText(word).width
            const spaceWidth = ctx.measureText(' ').width
            
            // Check if adding this word would exceed the line width
            const neededWidth = currentWidth + (currentLine.length > 0 ? spaceWidth : 0) + wordWidth
            
            if (neededWidth > maxWidth && currentLine.length > 0) {
              // Start a new line
              lines.push([...currentLine])
              currentLine = [{ text: word, bold: part.bold }]
              currentWidth = wordWidth
            } else {
              // Add space before the word if the line is not empty
              if (currentLine.length > 0) {
                currentLine.push({ text: ' ', bold: part.bold })
                currentWidth += spaceWidth
              }
              
              // Add the word
              currentLine.push({ text: word, bold: part.bold })
              currentWidth += wordWidth
            }
          }
        }
      }
      
      // Add the last line if it has content
      if (currentLine.length > 0) {
        lines.push(currentLine)
      }
      
      return lines
    }

    // Parse and wrap the text
    const parsedText = parseTextWithBold(textContent)
    const wrappedLines = wrapText(parsedText, maxWidth)
    
    // Draw the text
    ctx.fillStyle = '#000029' // Dark blue text color
    let currentY = textY
    
    for (const line of wrappedLines) {
      let currentX = textX
      
      for (const part of line) {
        if (part.text.trim() === '') {
          // Handle spaces
          ctx.font = `${fontSize}px AdriannaExtended-Regular, Arial, sans-serif`
          currentX += ctx.measureText(part.text).width
          continue
        }
        
        // Set font (bold or regular)
        ctx.font = `${fontSize}px ${part.bold ? 'AdriannaExtended-Bold' : 'AdriannaExtended-Regular'}, Arial, sans-serif`
        
        // Draw text part
        ctx.fillText(part.text, currentX, currentY)
        
        // Move X position for next part
        currentX += ctx.measureText(part.text).width
      }
      
      // Move to next line
      currentY += lineHeight
    }
  }

  // Generate canvas-based PDF and return blob URL for preview
  const generateCanvasPDF = async (): Promise<string | null> => {
    if (!partnerData || !effectiveQrCodeUrl) {
      toast.error('Missing partner data or QR code')
      return null
    }

    setIsGenerating(true)
    
    try {
      const template = selectedCanvasTemplate
      
      // Calculate dimensions in pixels (300 DPI)
      const pageWidth = template.size === 'A4' ? mmToPixels(210) : mmToPixels(297)
      const pageHeight = template.size === 'A4' ? mmToPixels(297) : mmToPixels(420)
      
      // Create canvas
      const canvas = document.createElement('canvas')
      canvas.width = pageWidth
      canvas.height = pageHeight
      const ctx = canvas.getContext('2d')
      
      if (!ctx) {
        throw new Error('Could not get canvas context')
      }

      // Load base template image
      const baseImage = await loadImage(template.baseImagePath)
      
      // Draw base template (scaled to fit canvas)
      ctx.drawImage(baseImage, 0, 0, pageWidth, pageHeight)
      
      // Load and draw logo if available
      if (logoUrl) {
        try {
          const logoImage = await loadImage(logoUrl)
          
          // Logo positioning: Different for A4 vs A3
          const logoTopMm = template.size === 'A4' ? 72 : 102 // A4: 72mm, A3: 102mm
          const logoBottomMm = template.size === 'A4' ? 97 : 138 // A4: 97mm, A3: 138mm
          const logoAreaHeight = logoBottomMm - logoTopMm // Available height
          const logoAreaCenterY = logoTopMm + (logoAreaHeight / 2) // Center point
          
          // Calculate logo position and size
          const logoX = mmToPixels(template.logoPosition.x) // Horizontal center
          const logoY = mmToPixels(logoAreaCenterY) // Vertical center
          
          // Scale logo to fit within the height constraint
          const maxLogoHeight = mmToPixels(logoAreaHeight) // Max height
          const logoAspect = logoImage.width / logoImage.height
          
          // Always limit by height, let width scale proportionally
          const logoHeight = Math.min(maxLogoHeight, logoImage.height)
          const logoWidth = logoHeight * logoAspect
          
          // Draw logo centered on the specified position
          ctx.drawImage(
            logoImage,
            logoX - logoWidth / 2, // Center horizontally
            logoY - logoHeight / 2, // Center vertically within the area
            logoWidth,
            logoHeight
          )
        } catch (_error) {
          // Continue without logo if it fails to load
        }
      }
      
      // Load and draw QR code
      try {
        const qrImage = await loadImage(effectiveQrCodeUrl)
        
        // Calculate QR position and size
        const qrX = mmToPixels(template.qrPosition.x)
        const qrY = mmToPixels(template.qrPosition.y)
        const qrWidth = mmToPixels(template.qrPosition.width)
        const qrHeight = mmToPixels(template.qrPosition.height)
        
        // Draw QR code (positioned from top-left corner of QR area)
        ctx.drawImage(qrImage, qrX, qrY, qrWidth, qrHeight)
      } catch (_error) {
        // Continue without QR code if it fails to load
      }

      // Add text content
      try {
        await addTextContent(ctx, template)
      } catch (_error) {
        // Continue without text content if it fails
      }
      
      // Optional: Add canvas to page for debugging (remove in production)
      if (process.env.NODE_ENV === 'development') {
        const debugCanvas = canvas.cloneNode(true) as HTMLCanvasElement
        const debugCtx = debugCanvas.getContext('2d')
        if (debugCtx) {
          debugCtx.drawImage(canvas, 0, 0)
        }
        debugCanvas.style.position = 'fixed'
        debugCanvas.style.top = '10px'
        debugCanvas.style.right = '10px'
        debugCanvas.style.width = '200px'
        debugCanvas.style.height = 'auto'
        debugCanvas.style.border = '2px solid red'
        debugCanvas.style.zIndex = '9999'
        debugCanvas.style.backgroundColor = 'white'
        document.body.appendChild(debugCanvas)
        
        // Remove debug canvas after 5 seconds
        setTimeout(() => {
          if (document.body.contains(debugCanvas)) {
            document.body.removeChild(debugCanvas)
          }
        }, 5000)
      }
      
      // Convert canvas to PDF
      const imgData = canvas.toDataURL('image/jpeg', 0.95)
      
      const pdf = new jsPDF({
        orientation: template.orientation,
        unit: 'mm',
        format: template.size === 'A4' ? [210, 297] : [297, 420]
      })
      
      // Add image to PDF (full page)
      pdf.addImage(
        imgData, 
        'JPEG', 
        0, 
        0, 
        template.size === 'A4' ? 210 : 297,
        template.size === 'A4' ? 297 : 420
      )
      
      // Generate blob URL for preview
      const pdfBlob = pdf.output('blob')
      const pdfUrl = URL.createObjectURL(pdfBlob)
      
      // Call the onGenerate callback
      await onGenerate({ 
        id: template.id, 
        name: template.name, 
        description: template.description,
        size: template.size, 
        orientation: template.orientation 
      })
      
      toast.success('PDF generated successfully!')
      return pdfUrl
    } catch (_error) {
      toast.error('Failed to generate PDF. Please try again.')
      return null
    } finally {
      setIsGenerating(false)
    }
  }

  // Handle PDF generation and set preview URL
  const handleGeneratePDF = async () => {
    const pdfUrl = await generateCanvasPDF()
    if (pdfUrl) {
      // Clean up previous URL if it exists
      if (generatedPdfUrl) {
        URL.revokeObjectURL(generatedPdfUrl)
      }
      setGeneratedPdfUrl(pdfUrl)
    }
  }

  // Export PDF function for download
  const exportPDF = async () => {
    if (!partnerData || !effectiveQrCodeUrl) {
      toast.error('Missing partner data or QR code')
      return
    }

    try {
      const template = selectedCanvasTemplate
      
      // Create canvas
      const canvas = document.createElement('canvas')
      const ctx = canvas.getContext('2d')
      if (!ctx) throw new Error('Could not get canvas context')

      // Set canvas size based on template (300 DPI for print quality)
      const dpi = 300
      canvas.width = template.size === 'A4' ? Math.round((210 * dpi) / 25.4) : Math.round((297 * dpi) / 25.4)
      canvas.height = template.size === 'A4' ? Math.round((297 * dpi) / 25.4) : Math.round((420 * dpi) / 25.4)

      // Load and draw base image
      const baseImg = await loadImage(template.baseImagePath)
      ctx.drawImage(baseImg, 0, 0, canvas.width, canvas.height)

      // Add logo if provided
      if (logoUrl) {
        const logoImg = await loadImage(logoUrl)
        
        // Logo positioning: Different for A4 vs A3 (same logic as preview)
        const logoTopMm = template.size === 'A4' ? 72 : 102 // A4: 72mm, A3: 102mm
        const logoBottomMm = template.size === 'A4' ? 97 : 138 // A4: 97mm, A3: 138mm
        const logoAreaHeight = logoBottomMm - logoTopMm // Available height
        const logoAreaCenterY = logoTopMm + (logoAreaHeight / 2) // Center point
        
        // Calculate logo position and size (same logic as preview)
        const logoX = mmToPixels(template.logoPosition.x) // Horizontal center
        const logoY = mmToPixels(logoAreaCenterY) // Vertical center
        
        // Scale logo to fit within the height constraint (same logic as preview)
        const maxLogoHeight = mmToPixels(logoAreaHeight) // Max height
        const logoAspect = logoImg.width / logoImg.height
        
        // Always limit by height, let width scale proportionally
        const logoHeight = Math.min(maxLogoHeight, logoImg.height)
        const logoWidth = logoHeight * logoAspect
        
        // Draw logo centered on the specified position (same logic as preview)
        ctx.drawImage(
          logoImg,
          logoX - logoWidth / 2, // Center horizontally
          logoY - logoHeight / 2, // Center vertically within the area
          logoWidth,
          logoHeight
        )
      }

      // Add QR code
      if (effectiveQrCodeUrl) {
        const qrImg = await loadImage(effectiveQrCodeUrl)
        const qrX = mmToPixels(template.qrPosition.x)
        const qrY = mmToPixels(template.qrPosition.y)
        const qrWidth = mmToPixels(template.qrPosition.width)
        const qrHeight = mmToPixels(template.qrPosition.height)
        ctx.drawImage(qrImg, qrX, qrY, qrWidth, qrHeight)
      }

      // Add text content
      await addTextContent(ctx, template)

      // Convert canvas to PDF
      const imgData = canvas.toDataURL('image/jpeg', 0.95)
      const pdf = new jsPDF({
        orientation: template.orientation,
        unit: 'mm',
        format: template.size
      })

      pdf.addImage(
        imgData, 
        'JPEG', 
        0, 
        0, 
        template.size === 'A4' ? 210 : 297,
        template.size === 'A4' ? 297 : 420
      )

      // Generate filename and download
      const filename = `${businessName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-referral-${template.id}.pdf`
      pdf.save(filename)
      
      toast.success('PDF downloaded successfully!')
    } catch (_error) {
      toast.error('Failed to export PDF. Please try again.')
    }
  }

  const openPDFInNewTab = () => {
    if (generatedPdfUrl) {
      window.open(generatedPdfUrl, '_blank')
    }
  }

  return (
    <div className="space-y-6">
      {/* Simplified Template Selection */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <FileText className="h-5 w-5" />
            <span>Generate Marketing Material</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Size Selection */}
          <div className="space-y-3">
            <label className="text-sm font-medium">Size</label>
            <div className="flex space-x-4">
              <label className="flex items-center space-x-2">
                <input
                  type="radio"
                  checked={selectedSize === 'A4'}
                  onChange={() => setSelectedSize('A4')}
                  className="text-primary"
                />
                <span className="text-sm">A4 (210 × 297mm)</span>
              </label>
              <label className="flex items-center space-x-2">
                <input
                  type="radio"
                  checked={selectedSize === 'A3'}
                  onChange={() => setSelectedSize('A3')}
                  className="text-primary"
                />
                <span className="text-sm">A3 (297 × 420mm)</span>
              </label>
            </div>
          </div>

          {/* Requirements Check */}
          <div className="space-y-3">
            <label className="text-sm font-medium">Requirements</label>
            <div className="space-y-2 text-sm">
              <div className="flex items-center space-x-2">
                {partnerData ? (
                  <CheckCircle className="h-4 w-4 text-green-500" />
                ) : (
                  <XCircle className="h-4 w-4 text-red-500" />
                )}
                <span className={partnerData ? 'text-green-700' : 'text-red-700'}>
                  Partner Data: {partnerData ? 'Available' : 'Missing'}
                </span>
              </div>
              <div className="flex items-center space-x-2">
                {effectiveQrCodeUrl ? (
                  <CheckCircle className="h-4 w-4 text-green-500" />
                ) : (
                  <XCircle className="h-4 w-4 text-red-500" />
                )}
                <span className={effectiveQrCodeUrl ? 'text-green-700' : 'text-red-700'}>
                  QR Code: {effectiveQrCodeUrl ? (qrCodeUrl ? 'Generated' : 'Auto-generated') : 'Missing partner code'}
                </span>
              </div>
              <div className="flex items-center space-x-2">
                {logoUrl ? (
                  <CheckCircle className="h-4 w-4 text-green-500" />
                ) : (
                  <AlertCircle className="h-4 w-4 text-yellow-500" />
                )}
                <span className={logoUrl ? 'text-green-700' : 'text-yellow-700'}>
                  Logo: {logoUrl ? 'Uploaded' : 'Optional'}
                </span>
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <Button
            onClick={handleGeneratePDF}
            disabled={!canGenerate || isGenerating}
            className="w-full"
            size="lg"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <FileText className="mr-2 h-4 w-4" />
                Generate Marketing Material
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* PDF Preview */}
      {generatedPdfUrl && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Eye className="h-5 w-5" />
              <span>Generated PDF Preview</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {/* PDF Preview */}
              <div 
                className="border rounded-lg overflow-hidden cursor-pointer hover:shadow-lg transition-shadow"
                onClick={openPDFInNewTab}
                title="Click to open PDF in new tab"
              >
                <iframe
                  src={generatedPdfUrl}
                  className="w-full h-96 pointer-events-none"
                  title="PDF Preview"
                />
              </div>
              
              {/* Preview Actions */}
              <div className="flex items-center justify-between">
                <p className="text-sm text-muted-foreground">
                  Click preview to open in new tab • {selectedSize} format
                </p>
                <Button
                  onClick={exportPDF}
                  variant="outline"
                  size="sm"
                  className="flex items-center space-x-2"
                >
                  <Download className="h-4 w-4" />
                  <span>Download PDF</span>
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}



      {/* Printing Tips */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Printer className="h-5 w-5" />
            <span>Printing Tips</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4 text-sm">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-3">
                <div>
                  <h4 className="font-medium text-foreground mb-2">Paper Quality</h4>
                  <ul className="space-y-1 text-muted-foreground">
                    <li>• Use high-quality paper (200-300gsm recommended)</li>
                    <li>• Matte or satin finish works best</li>
                    <li>• Avoid glossy paper for better QR code scanning</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-medium text-foreground mb-2">Print Settings</h4>
                  <ul className="space-y-1 text-muted-foreground">
                    <li>• Print at 100% scale (no fit-to-page)</li>
                    <li>• Use high quality/best print mode</li>
                    <li>• Ensure QR code is sharp and clear</li>
                  </ul>
                </div>
              </div>
              <div className="space-y-3">
                <div>
                  <h4 className="font-medium text-foreground mb-2">Durability</h4>
                  <ul className="space-y-1 text-muted-foreground">
                    <li>• Consider laminating for outdoor use</li>
                    <li>• Use UV-resistant ink for longevity</li>
                    <li>• Store in dry conditions when not in use</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-medium text-foreground mb-2">Display</h4>
                  <ul className="space-y-1 text-muted-foreground">
                    <li>• Place at eye level for best visibility</li>
                    <li>• Ensure good lighting for QR code scanning</li>
                    <li>• Keep materials clean and unfolded</li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-blue-800 font-medium">💡 Pro Tip</p>
              <p className="text-blue-700 text-sm mt-1">
                Laminate your materials for durability and professional appearance. This protects against weather and wear, making them perfect for outdoor displays or high-traffic areas.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
} 